# Generated by Django 4.0.2 on 2022-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviewed',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
