# Generated by Django 4.0.2 on 2022-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='ticket',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=8192),
        ),
        migrations.AddField(
            model_name='review',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reviewed',
            field=models.CharField(default='false', max_length=7),
        ),
    ]
