# Generated by Django 4.0.2 on 2022-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_user_review_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='review',
            name='header_image',
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
    ]
