# Generated by Django 4.0.2 on 2022-05-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_title_review_headline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='date_posted',
        ),
    ]
