# Generated by Django 4.0.2 on 2022-09-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_post_type_review_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='body',
        ),
    ]
