# Generated by Django 4.0.2 on 2022-03-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_followers_user_delete_userfollows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('follow_time',
                 models.DateTimeField(
                     auto_now=True)),
                ('follower',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='follower',
                     to=settings.AUTH_USER_MODEL)),
                ('following',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='following',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {
                    (
                        'following',
                        'follower')},
            },
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
